<a href="https://colab.research.google.com/github/Saichand-design/MLOPs/blob/main/train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('/content/diabetic.txt')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              40 non-null     int64  
 1   BMI              40 non-null     float64
 2   Blood Pressure   40 non-null     int64  
 3   Glucose Level    40 non-null     int64  
 4   Insulin Level    40 non-null     int64  
 5   Diabetic Status  40 non-null     object 
dtypes: float64(1), int64(4), object(1)
memory usage: 2.0+ KB


In [6]:
df['Dstats'] = np.where(df['Diabetic Status']=='Yes',1,0)
df['Dstats']


,Dstats
0,1
1,1
2,0
3,1
4,1
5,0
6,0
7,1
8,0
9,1


In [7]:
xdf = df.drop(['Diabetic Status','Dstats'], axis = 1)
xdf.head()

,Age,BMI,Blood Pressure,Glucose Level,Insulin Level
0,45,25.3,120,140,85
1,50,28.1,130,155,90
2,38,23.5,115,110,75
3,60,31.2,135,160,95
4,55,29.8,128,150,92


In [8]:
X = xdf.to_numpy()
X

array([[ 45. ,  25.3, 120. , 140. ,  85. ],
       [ 50. ,  28.1, 130. , 155. ,  90. ],
       [ 38. ,  23.5, 115. , 110. ,  75. ],
       [ 60. ,  31.2, 135. , 160. ,  95. ],
       [ 55. ,  29.8, 128. , 150. ,  92. ],
       [ 32. ,  22.7, 110. , 105. ,  70. ],
       [ 42. ,  26.5, 118. , 135. ,  80. ],
       [ 48. ,  27.3, 125. , 145. ,  88. ],
       [ 35. ,  24.1, 113. , 120. ,  78. ],
       [ 58. ,  30.5, 132. , 158. ,  93. ],
       [ 41. ,  25.8, 121. , 138. ,  82. ],
       [ 47. ,  27. , 126. , 144. ,  87. ],
       [ 36. ,  24.9, 114. , 122. ,  76. ],
       [ 53. ,  29.1, 130. , 148. ,  89. ],
       [ 40. ,  26. , 119. , 132. ,  81. ],
       [ 61. ,  31.5, 136. , 162. ,  96. ],
       [ 39. ,  23.8, 117. , 128. ,  77. ],
       [ 49. ,  27.5, 129. , 146. ,  90. ],
       [ 37. ,  24.5, 116. , 124. ,  79. ],
       [ 54. ,  30. , 133. , 150. ,  91. ],
       [ 46. ,  26.1, 122. , 142. ,  86. ],
       [ 51. ,  28.5, 131. , 156. ,  91. ],
       [ 34. ,  23.1, 111. , 108

In [9]:
y = df['Dstats'].to_numpy()
y

array([1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [10]:
y.shape

(40,)

In [11]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)


LinearRegression()

In [12]:
from sklearn.metrics import r2_score
ycap = model.predict(X)
ycap


array([ 0.86184806,  0.86462384,  0.27911111,  1.12527181,  0.97135933,
       -0.23812176,  0.10321851,  0.82704668,  0.16835346,  1.01267411,
        0.33589457,  0.76577175, -0.11318521,  0.78897636,  0.20552768,
        1.18318298,  0.30077076,  0.998184  ,  0.24634483,  0.81076822,
        0.82179848,  0.90992162, -0.0769397 ,  1.20110651,  1.04926431,
       -0.35408322,  0.12852247,  0.80834635, -0.14001739,  1.03260598,
        0.27384284,  0.62159732,  0.11598717,  0.71386021,  0.19162081,
        1.22641048,  0.20314178,  1.06347559, -0.1053774 ,  0.81729468])

In [13]:
np.c_[y,ycap]

array([[ 1.        ,  0.86184806],
       [ 1.        ,  0.86462384],
       [ 0.        ,  0.27911111],
       [ 1.        ,  1.12527181],
       [ 1.        ,  0.97135933],
       [ 0.        , -0.23812176],
       [ 0.        ,  0.10321851],
       [ 1.        ,  0.82704668],
       [ 0.        ,  0.16835346],
       [ 1.        ,  1.01267411],
       [ 0.        ,  0.33589457],
       [ 1.        ,  0.76577175],
       [ 0.        , -0.11318521],
       [ 1.        ,  0.78897636],
       [ 0.        ,  0.20552768],
       [ 1.        ,  1.18318298],
       [ 0.        ,  0.30077076],
       [ 1.        ,  0.998184  ],
       [ 0.        ,  0.24634483],
       [ 1.        ,  0.81076822],
       [ 1.        ,  0.82179848],
       [ 1.        ,  0.90992162],
       [ 0.        , -0.0769397 ],
       [ 1.        ,  1.20110651],
       [ 1.        ,  1.04926431],
       [ 0.        , -0.35408322],
       [ 0.        ,  0.12852247],
       [ 1.        ,  0.80834635],
       [ 0.        ,

In [14]:
acc = r2_score(y,ycap)
acc

0.8459988570808885

In [15]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR as svr

model2 = svr(kernel = 'linear')
model2.fit(X,y)
ycap2 = model2.predict(X)
ycap2


array([ 0.90650071,  0.89678273,  0.23912674,  1.09794973,  0.97683243,
       -0.27311431,  0.09875065,  0.86368899,  0.22757015,  0.98818867,
        0.36914241,  0.79344215, -0.10407946,  0.76021106,  0.23594617,
        1.1575255 ,  0.28878784,  1.04039677,  0.28887386,  0.7899871 ,
        0.86222454,  0.94252335, -0.10465657,  1.17639069,  1.0567635 ,
       -0.39354645,  0.12413597,  0.85251466, -0.10495658,  1.00497839,
        0.30658641,  0.65025986,  0.13933525,  0.71851348,  0.21293005,
        1.20177601,  0.22243041,  1.10649268, -0.09503454,  0.80648309])

In [16]:
np.c_[y,ycap2]

array([[ 1.        ,  0.90650071],
       [ 1.        ,  0.89678273],
       [ 0.        ,  0.23912674],
       [ 1.        ,  1.09794973],
       [ 1.        ,  0.97683243],
       [ 0.        , -0.27311431],
       [ 0.        ,  0.09875065],
       [ 1.        ,  0.86368899],
       [ 0.        ,  0.22757015],
       [ 1.        ,  0.98818867],
       [ 0.        ,  0.36914241],
       [ 1.        ,  0.79344215],
       [ 0.        , -0.10407946],
       [ 1.        ,  0.76021106],
       [ 0.        ,  0.23594617],
       [ 1.        ,  1.1575255 ],
       [ 0.        ,  0.28878784],
       [ 1.        ,  1.04039677],
       [ 0.        ,  0.28887386],
       [ 1.        ,  0.7899871 ],
       [ 1.        ,  0.86222454],
       [ 1.        ,  0.94252335],
       [ 0.        , -0.10465657],
       [ 1.        ,  1.17639069],
       [ 1.        ,  1.0567635 ],
       [ 0.        , -0.39354645],
       [ 0.        ,  0.12413597],
       [ 1.        ,  0.85251466],
       [ 0.        ,

In [17]:
acc = r2_score(y,ycap2)
acc

0.8423374586277426

In [18]:
import joblib

In [19]:
joblib.dump(model,"diabetics_model.pkl")

['diabetics_model.pkl']

In [33]:
from fastapi import FastAPI
from pydantic import BaseModel


In [34]:
app = FastAPI()
model = joblib.load("diabetics_model.pkl")

In [37]:
class DiabetiesInput(BaseModel):
    Age	:int
    BMI	: float
    BloodPressure : float
    GlucoseLevel	: float
    InsulinLevel : float

@app.get("/")
def read_root():
    return {"Message": f"DiabeticPredictionAPI is live"}

@app.post('/predict')
def predict_diabetics(data: DiabetiesInput):
    input_data = np.array([data.Age, data.BMI, data.BloodPressure, data.GlucoseLevel, data.InsulinLevel])
    prediction = model.predict(input_data.reshape(1, -1)) # Reshape for single prediction
    return {"Prediction": prediction.tolist()[0]} # Convert numpy array to list for JSON response